services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mesominds-frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mesominds-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=${VITE_API_URL}

networks:
  mesominds-network:
    external: true